# Generated by Django 4.1.13 on 2024-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('delivered', 'Delivered'), ('in progress', 'In progress'), ('canceled', 'Canceled')], default='ordered', max_length=100),
        ),
    ]
