# Generated by Django 4.1.13 on 2024-08-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default='jlassi.mohamedhani@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('delivered', 'Delivered'), ('in progress', 'In progress'), ('canceled', 'Canceled')], default='in progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.supplier'),
        ),
    ]
